DISEASE_INFO = {
    "Apple___Apple_scab": {
        "name": "Apple Scab",
        "cause": "Caused by fungus Venturia inaequalis. Spreads via rain splash in spring when temperatures are 15-25°C.",
        "precautions": [
            "Rake and destroy fallen leaves in autumn",
            "Prune trees to improve air circulation",
            "Apply fungicide at green tip stage",
            "Plant resistant varieties like Liberty or Enterprise",
        ],
        "treatment": "Spray Captan or Myclobutanil fungicide every 7-10 days starting at green tip. Remove heavily infected branches.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Apple___Black_rot": {
        "name": "Apple Black Rot",
        "cause": "Caused by fungus Botryosphaeria obtusa. Enters through wounds and affects fruit, leaves, and branches.",
        "precautions": [
            "Remove mummified fruit from trees",
            "Prune out infected branches well below affected area",
            "Avoid wounding fruit during handling",
            "Remove prunings from orchard",
        ],
        "treatment": "Apply captan or benzimidazole fungicides. Remove infected plant parts immediately. Destroy fallen debris.",
        "severity": "High",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Apple___Cedar_apple_rust": {
        "name": "Cedar Apple Rust",
        "cause": "Caused by fungus Gymnosporangium juniperi-virginianae. Requires both apple and cedar/juniper hosts to complete life cycle.",
        "precautions": [
            "Remove cedar galls within 1km of orchard",
            "Plant resistant apple varieties",
            "Apply sulfur fungicide as preventive",
            "Avoid planting junipers near apple trees",
        ],
        "treatment": "Apply myclobutanil or propiconazole at pink stage and every 10 days. Remove and destroy cedar galls.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Apple___healthy": {
        "name": "Healthy Apple",
        "cause": "No disease detected. Plant is healthy.",
        "precautions": [
            "Maintain regular watering schedule",
            "Monitor for early signs of disease",
            "Keep area clean of fallen debris",
        ],
        "treatment": "No treatment needed. Continue regular care with balanced fertilization.",
        "severity": "None",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Blueberry___healthy": {
        "name": "Healthy Blueberry",
        "cause": "No disease detected. Plant is healthy.",
        "precautions": [
            "Maintain acidic soil pH of 4.5-5.5",
            "Regular pruning for air circulation",
            "Monitor for pest activity",
        ],
        "treatment": "No treatment needed. Continue regular care.",
        "severity": "None",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Cherry___Powdery_mildew": {
        "name": "Cherry Powdery Mildew",
        "cause": "Caused by fungus Podosphaera clandestina. Thrives in warm, humid conditions with poor air circulation.",
        "precautions": [
            "Plant resistant varieties",
            "Prune for good air circulation",
            "Avoid overhead irrigation",
            "Remove infected plant parts",
        ],
        "treatment": "Apply sulfur-based fungicide or powdery mildew specific fungicides. Repeat every 7-10 days.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Cherry___healthy": {
        "name": "Healthy Cherry",
        "cause": "No disease detected. Plant is healthy.",
        "precautions": [
            "Proper spacing for air circulation",
            "Regular monitoring",
            "Adequate watering",
        ],
        "treatment": "No treatment needed. Continue regular care.",
        "severity": "None",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Corn___Cercospora_leaf_spot": {
        "name": "Cercospora Leaf Spot (Gray Leaf Spot)",
        "cause": "Caused by fungus Cercospora zeae-maydis. Spreads in warm, humid conditions (25-30°C).",
        "precautions": [
            "Rotate crops with non-grass crops",
            "Use resistant hybrids",
            "Tillage to bury crop residue",
            "Balanced fertilization",
        ],
        "treatment": "Apply azoxystrobin or pyraclostrobin fungicide at tasseling. Early detection is crucial.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Corn___Common_rust": {
        "name": "Common Rust",
        "cause": "Caused by fungus Puccinia sorghi. Develops in cool (15-25°C) and humid conditions.",
        "precautions": [
            "Plant resistant corn varieties",
            "Monitor fields regularly",
            "Remove infected leaves early",
            "Avoid late planting",
        ],
        "treatment": "Apply triazole fungicides (propiconazole) if severe. Usually not economically damaging.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Corn___Northern_Leaf_Blight": {
        "name": "Northern Leaf Blight",
        "cause": "Caused by fungus Setosphaeria turcica. Favors moderate temperatures (18-25°C) with high humidity.",
        "precautions": [
            "Use resistant hybrids",
            "Crop rotation",
            "Remove infected debris",
            "Balanced nitrogen fertilization",
        ],
        "treatment": "Apply foliar fungicides (azoxystrobin, pyraclostrobin) at disease onset. Scout regularly.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Corn___healthy": {
        "name": "Healthy Corn",
        "cause": "No disease detected. Plant is healthy.",
        "precautions": [
            "Regular monitoring",
            "Proper fertilization",
            "Adequate irrigation",
        ],
        "treatment": "No treatment needed. Continue regular care.",
        "severity": "None",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Grape___Black_rot": {
        "name": "Grape Black Rot",
        "cause": "Caused by fungus Guignardia bidwellii. Overwinters on infected plant debris. Spreads in warm, wet spring weather.",
        "precautions": [
            "Remove infected plant parts and mummified fruit",
            "Improve air circulation through pruning",
            "Apply preventive fungicides",
            "Remove leaf litter",
        ],
        "treatment": "Apply captan or myclobutanil from bloom through veraison. Remove infected clusters immediately.",
        "severity": "High",
        "severity_score": 3,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Grape___Esca": {
        "name": "Esca (Black Measles)",
        "cause": "Caused by multiple fungi including Phaeomoniella chlamydospora. Enters through pruning wounds.",
        "precautions": [
            "Prune during dry weather",
            "Avoid wounding during wet periods",
            "Use wound protectants",
            "Remove heavily infected vines",
        ],
        "treatment": "No effective chemical control. Remove and destroy infected vines. Apply fungicides as preventive.",
        "severity": "High",
        "severity_score": 3,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Grape___Leaf_blight": {
        "name": "Grape Leaf Blight (Isariopsis Leaf Spot)",
        "cause": "Caused by fungus Isariopsis clavispora. Favors warm, humid conditions.",
        "precautions": [
            "Remove infected leaves",
            "Improve air circulation",
            "Avoid overhead irrigation",
            "Remove plant debris",
        ],
        "treatment": "Apply copper-based or synthetic fungicides. Start applications at first sign of infection.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Grape___healthy": {
        "name": "Healthy Grape",
        "cause": "No disease detected. Plant is healthy.",
        "precautions": [
            "Proper pruning",
            "Regular monitoring",
            "Adequate drainage",
        ],
        "treatment": "No treatment needed. Continue regular care.",
        "severity": "None",
        "severity_score": 0,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Orange___Haunglongbing": {
        "name": "Huanglongbing (Citrus Greening)",
        "cause": "Caused by bacterium Candidatus Liberibacter asiaticus transmitted by Asian citrus psyllid. Cannot be cured once infected.",
        "precautions": [
            "Control psyllid population with insecticides",
            "Use disease-free planting material",
            "Remove infected trees promptly",
            "Use reflective mulch to deter psyllids",
        ],
        "treatment": "No cure exists. Remove infected trees to prevent spread. Use preventive insecticides for psyllids.",
        "severity": "High",
        "severity_score": 3,
        "affected_part": "Whole plant",
        "spread": "Insect (Psyllid)",
        "season": "Year-round",
        "organic_treatment": "No organic cure. Remove infected trees immediately.",
        "consult_expert": True,  
        
    },
    "Peach___Bacterial_spot": {
        "name": "Peach Bacterial Spot",
        "cause": "Caused by bacterium Xanthomonas arboricola pv. pruni. Spreads via rain splash, favors warm, wet conditions.",
        "precautions": [
            "Plant resistant varieties",
            "Avoid overhead irrigation",
            "Remove infected plant debris",
            "Prune for air circulation",
        ],
        "treatment": "Apply copper-based bactericides during dormancy and after petal fall. Remove severely infected trees.",
        "severity": "Medium",
       "severity_score": 2,
        "affected_part": "Whole plant",
        "spread": "Insect (Psyllid)",
        "season": "Year-round",
        "organic_treatment": "No organic cure. Remove infected trees immediately.",
        "consult_expert": True,  
    },
    "Peach___healthy": {
        "name": "Healthy Peach",
        "cause": "No disease detected. Plant is healthy.",
        "precautions": [
            "Proper pruning",
            "Regular monitoring",
            "Balanced fertilization",
        ],
        "treatment": "No treatment needed. Continue regular care.",
        "severity": "None",
        "severity_score": 0,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Pepper___Bacterial_spot": {
        "name": "Pepper Bacterial Spot",
        "cause": "Caused by bacterium Xanthomonas campestris pv. vesicatoria. Spreads through splashing water and handling.",
        "precautions": [
            "Use certified disease-free seeds",
            "Rotate crops",
            "Avoid overhead irrigation",
            "Remove infected plant debris",
        ],
        "treatment": "Apply copper-based bactericides. Remove and destroy heavily infected plants. Use resistant varieties.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Pepper___healthy": {
        "name": "Healthy Pepper",
        "cause": "No disease detected. Plant is healthy.",
        "precautions": [
            "Regular monitoring",
            "Proper spacing",
            "Adequate watering",
        ],
        "treatment": "No treatment needed. Continue regular care.",
        "severity": "None",
        "severity_score": 0,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Potato___Early_blight": {
        "name": "Potato Early Blight",
        "cause": "Caused by fungus Alternaria solani. Favors warm (24-29°C), humid conditions and may develop on stressed plants.",
        "precautions": [
            "Rotate crops (3-4 year rotation)",
            "Remove infected plant debris",
            "Avoid overhead irrigation",
            "Use resistant varieties",
        ],
        "treatment": "Apply chlorothalonil or copper fungicide. Remove lower infected leaves. Maintain proper nutrition.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Potato___Late_blight": {
        "name": "Potato Late Blight",
        "cause": "Caused by oomycete Phytophthora infestans. Spreads rapidly in cool (15-22°C), wet conditions. Highly destructive.",
        "precautions": [
            "Use certified disease-free seed potatoes",
            "Destroy volunteer plants",
            "Improve air circulation",
            "Hill soil around plants",
        ],
        "treatment": "Apply mancozeb or metalaxyl fungicide preventively. Destroy infected plants immediately. Do not compost.",
        "severity": "High",
        "severity_score": 3,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Potato___healthy": {
        "name": "Healthy Potato",
        "cause": "No disease detected. Plant is healthy.",
        "precautions": [
            "Regular monitoring",
            "Proper hilling",
            "Adequate irrigation",
        ],
        "treatment": "No treatment needed. Continue regular care.",
        "severity": "None",
        "severity_score": 0,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Raspberry___healthy": {
        "name": "Healthy Raspberry",
        "cause": "No disease detected. Plant is healthy.",
        "precautions": [
            "Proper pruning",
            "Regular monitoring",
            "Good air circulation",
        ],
        "treatment": "No treatment needed. Continue regular care.",
        "severity": "None",
        "severity_score": 0,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Soybean___healthy": {
        "name": "Healthy Soybean",
        "cause": "No disease detected. Plant is healthy.",
        "precautions": [
            "Crop rotation",
            "Regular monitoring",
            "Proper weed control",
        ],
        "treatment": "No treatment needed. Continue regular care.",
        "severity": "None",
        "severity_score": 0,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Squash___Powdery_mildew": {
        "name": "Squash Powdery Mildew",
        "cause": "Caused by fungus Erysiphe cichoracearum. Thrives in warm, dry days with humid nights.",
        "precautions": [
            "Plant resistant varieties",
            "Improve air circulation",
            "Avoid overhead watering",
            "Remove infected leaves",
        ],
        "treatment": "Apply sulfur-based fungicide or powdery mildew specific products. Neem oil also effective.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Strawberry___Leaf_scorch": {
        "name": "Strawberry Leaf Scorch",
        "cause": "Caused by fungus Diplocarpon earliana. Spreads via splashing water and contaminated planting material.",
        "precautions": [
            "Use disease-free transplants",
            "Remove infected leaves",
            "Avoid overhead irrigation",
            "Mulch to prevent splash",
        ],
        "treatment": "Apply captan or other fungicides. Remove and destroy infected plant debris. Use resistant varieties.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Strawberry___healthy": {
        "name": "Healthy Strawberry",
        "cause": "No disease detected. Plant is healthy.",
        "precautions": [
            "Proper mulching",
            "Regular monitoring",
            "Adequate watering",
        ],
        "treatment": "No treatment needed. Continue regular care.",
        "severity": "None",
        "severity_score": 0,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Tomato___Bacterial_spot": {
        "name": "Tomato Bacterial Spot",
        "cause": "Caused by bacterium Xanthomonas vesicatoria. Spreads through splashing water, handling, and contaminated seeds.",
        "precautions": [
            "Use disease-free seeds",
            "Rotate crops",
            "Avoid overhead irrigation",
            "Remove infected plant debris",
        ],
        "treatment": "Apply copper-based bactericides. Remove heavily infected plants. Use resistant varieties.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Tomato___Early_blight": {
        "name": "Tomato Early Blight",
        "cause": "Caused by fungus Alternaria solani. Favored by warm, humid weather and weak plant growth.",
        "precautions": [
            "Rotate crops yearly",
            "Avoid wetting foliage while watering",
            "Remove lower infected leaves",
            "Use mulching",
        ],
        "treatment": "Apply chlorothalonil or copper fungicide. Repeat every 7-14 days. Remove infected debris.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Tomato___Late_blight": {
        "name": "Tomato Late Blight",
        "cause": "Caused by oomycete Phytophthora infestans. Spreads rapidly in cool, wet conditions. Can destroy entire crop in days.",
        "precautions": [
            "Avoid overhead irrigation",
            "Remove and destroy infected plant debris",
            "Ensure good air circulation",
            "Use resistant varieties",
        ],
        "treatment": "Spray with mancozeb or copper-based fungicide every 7 days. Remove infected leaves immediately.",
        "severity": "High",
        "severity_score": 3,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Tomato___Leaf_Mold": {
        "name": "Tomato Leaf Mold",
        "cause": "Caused by fungus Passalora fulva. Develops in high humidity (85%+) and warm temperatures (22-25°C).",
        "precautions": [
            "Improve ventilation in greenhouse",
            "Avoid overhead watering",
            "Remove infected leaves",
            "Reduce humidity",
        ],
        "treatment": "Apply copper fungicide or chlorothalonil. Improve air circulation. Remove infected leaves.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Tomato___Septoria_leaf_spot": {
        "name": "Tomato Septoria Leaf Spot",
        "cause": "Caused by fungus Septoria lycopersici. Spreads via splashing water, favors warm, wet conditions.",
        "precautions": [
            "Remove infected plant debris",
            "Rotate crops",
            "Avoid overhead irrigation",
            "Space plants properly",
        ],
        "treatment": "Apply copper-based fungicide or chlorothalonil. Remove infected leaves. Improve air circulation.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Tomato___Spider_mites": {
        "name": "Tomato Spider Mites",
        "cause": "Caused by spider mite pests (Tetranychus urticae). Thrives in hot, dry conditions.",
        "precautions": [
            "Maintain adequate irrigation",
            "Avoid water stress",
            "Monitor regularly",
            "Encourage predatory insects",
        ],
        "treatment": "Apply miticide or insecticidal soap. Increase humidity. Remove heavily infested leaves.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
        
    },
    "Tomato___Target_Spot": {
        "name": "Tomato Target Spot",
        "cause": "Caused by fungus Corynespora cassiicola. Favors warm, humid conditions and weakened plants.",
        "precautions": [
            "Rotate crops",
            "Remove infected debris",
            "Avoid overhead irrigation",
            "Control weeds",
        ],
        "treatment": "Apply broad-spectrum fungicides. Remove infected plant parts. Improve drainage and air circulation.",
        "severity": "Medium",
        "severity_score": 2,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "name": "Tomato Yellow Leaf Curl Virus",
        "cause": "Caused by begomovirus transmitted by whiteflies. Infected plants cannot be cured.",
        "precautions": [
            "Control whitefly population",
            "Use reflective mulch",
            "Remove infected plants immediately",
            "Use resistant varieties",
        ],
        "treatment": "No cure exists. Remove infected plants to prevent spread. Control whiteflies with insecticides.",
        "severity": "High",
        "severity_score": 3,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Tomato___Tomato_mosaic_virus": {
        "name": "Tomato Mosaic Virus",
        "cause": "Caused by tobamovirus transmitted mechanically through handling and contaminated tools.",
        "precautions": [
            "Disinfect tools and hands",
            "Use disease-free seeds",
            "Control insect vectors",
            "Remove infected plants",
        ],
        "treatment": "No cure exists. Remove infected plants. Disinfect all tools. Use resistant varieties.",
        "severity": "High",
        "severity_score": 3,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
    "Tomato___healthy": {
        "name": "Healthy Tomato",
        "cause": "No disease detected. Plant is healthy.",
        "precautions": [
            "Maintain regular watering",
            "Monitor for early signs",
            "Keep area clean",
        ],
        "treatment": "No treatment needed. Continue regular care.",
        "severity": "None",
        "severity_score": 0,          # 0=None 1=Low 2=Medium 3=High — useful for sorting/filtering
        "affected_part": "Leaves, Fruit",
        "spread": "Rain, Wind",
        "season": "Spring",
        "organic_treatment": "Spray neem oil or sulfur-based fungicide as an organic alternative.",
        "consult_expert": False, 
    },
}


def get_disease_info(class_name: str) -> dict:
    return DISEASE_INFO.get(
        class_name,
        {
            "name": class_name.replace("___", " - ").replace("_", " "),
            "cause": "Information not available.",
            "precautions": ["Consult a local agricultural expert"],
            "treatment": "Consult a local agricultural expert.",
            "severity": "Unknown",
        },
    )
